package com.cy.core.user.dao;

import com.cy.core.user.entity.UserAuth;

public interface UserAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_user_auth
     *
     * @mbggenerated Thu Jul 27 16:13:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_user_auth
     *
     * @mbggenerated Thu Jul 27 16:13:49 CST 2017
     */
    int insert(UserAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_user_auth
     *
     * @mbggenerated Thu Jul 27 16:13:49 CST 2017
     */
    int insertSelective(UserAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_user_auth
     *
     * @mbggenerated Thu Jul 27 16:13:49 CST 2017
     */
    UserAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_user_auth
     *
     * @mbggenerated Thu Jul 27 16:13:49 CST 2017
     */
    int updateByPrimaryKeySelective(UserAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cy_user_auth
     *
     * @mbggenerated Thu Jul 27 16:13:49 CST 2017
     */
    int updateByPrimaryKey(UserAuth record);
    
    //检测token是否有效
    int selectCheckToken(UserAuth record);
    
    //检测rftoken是否有效
    int selectCheckRFToken(UserAuth record);
    
	void deleteByuserid(UserAuth userAuth);
	
	void deleteByToken(String token);
	
	int updatetoken(UserAuth record);
	
	int updatetokenfhstatus(UserAuth record);
}